### PR TITLE
new landing Page for Kenya

### PR DESCRIPTION
**Pull request by pomareta**
compile it please
The group is NTD_LSH_LandingPage_KEN = "aQt4ynXtBOS";
`$ yarn extract-pot && for %pofile in i18n/*.po; do msgmerge --backup=off -U $pofile i18n/en.pot; done` not working in my windows

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@pomareta on a quick functional test in 2.30, looks like event visualizer is not properly working. You might want to test it in 2.34, as you're using links to Event Capture and Reports, and Maps, that have changed in 2.34. Provided the zip file through Slack

**Comment by ifoche** [comment]
@pomareta the new version of the app, with the last changes, is available for your test in TRAINING and PREPROD. If you validate them please let us know in this PR. Thanks!

**Review by SferaDev — APPROVED** [review]
Everything looks fine on my side @ifoche

**Comment by ifoche** [comment]
@pomareta confirmed by Slack, everything looks fine for him, so merging and releasing

**Review by ifoche — APPROVED** [review]
thanks @pomareta and @SferaDev

**Pull request merged**
